#!/bin/false # ~/.bashrc is *sourced* by bash(1) for non-login shells.
# Also sourced by login shells per instruction in .profile.

# See /usr/share/doc/bash/examples/startup-files (in the package bash-doc) for
# examples

# If not running interactively, don't do anything.
[ -z "$PS1" ] && return
# Above is unreliable; also check invocation options
[[ "$-" =~ i ]] || return

[ "$_BASHRC_APPLIED" ] && return
echo "Sourcing ~/.bashrc"
# Nothing here (Aliases, functions, and completions) exports to subshells, and
# /etc/bash.bashrc clobbers whatever was in PS1; we always have to set it. So
# don't offer this guard to subshells.
# export _BASHRC_APPLIED=1
_BASHRC_APPLIED=1

# Always set the prompt, since /etc/bash.bashrc and /etc/profile set it
# regardless of what's in the environment (I think that is a bug!) :(

function ps1_context {
	# For any of these bits of context that exist, display them and append a
	# space.
	virtualenv=`basename "$VIRTUAL_ENV"`
	for v in "$debian_chroot" "$virtualenv" "$PS1_CONTEXT"; do
		echo -n "${v:+$v }"
	done
	# Take advantage of the fricken awesome tools from
	# /etc/bash_completion.d/git
	__git_ps1 "±%s "
}

function ps1_curdir {
		p="${PWD/$VIRTUAL_ENV/♬}"
		echo "${p/$HOME/~}"
}

if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	if [ "$VIRTUAL_ENV" ]; then
		p='\w'
	else
		p=
	fi
	PS1='\[\033[;1;31m\]$(ps1_context)\[\033[;1;3'${PS1_HOSTCOLOR:-7}'m\]\u@\h\[\033[m\]:\[\033[1;34m\]$(ps1_curdir)\[\033[m\]\$ '
else
	PS1="$(ps1_context)"'\u@\h:$(ps1_curdir)\$ '
fi

if [ -f ~/.bash_aliases ]; then
	. ~/.bash_aliases
fi

if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
	# Ugh! Can't export completion rules to subshells, so we're forced to
	# source bash_completion every single time a shell is spawned! I wish I
	# could spawn a 'completion daemon' that sits in the background for bash to
	# talk to, rather than crap up my environment and wait a half second every
	# time I invoke a shell to re-load completion rules that haven't changed.
	echo -n "Sourcing /etc/bash_completion..."
	. /etc/bash_completion
	echo
fi

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary, update the values
# of LINES and COLUMNS.
shopt -s checkwinsize

# Source private/local bashrc.
[ -f ~/.bashrc.local ] && . ~/.bashrc.local
