#!/bin/sh
echo "Sourcing ~/.bash_aliases"

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='ls --color=auto --format=vertical'
    #alias vdir='ls --color=auto --format=long'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# vi = gvim when running graphical.
if [ -n "$DISPLAY" ]; then
	alias vi=gvim
	alias v=gvim
else
	alias vi=vim
	alias v=vim
fi

alias nautilus="nautilus --no-desktop --browser"
# Can also be achieved with:
# 	gconftool --set /apps/nautilus/preferences/show_desktop false --type boolean
# 	gconftool --set /apps/nautilus/preferences/always_use_browser true --type boolean
alias smbclient="smbclient -A .smb/auth"
alias svngvimdiff="svn diff --diff-cmd gvimdiff-svn-wrapper"
alias gitgvimdiff="GIT_EXTERNAL_DIFF=gvimdiff-git-diff-wrapper git diff"

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'
