#!/bin/false # This file is sourced by bash(1) for login shells.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# Useful for debugging startup execution path.
echo "Sourcing ~/.profile"
export _PROFILE_APPLIED=1

# the default umask is set in /etc/login.defs
#umask 022

# prepend private bin(s) and man(s) if they exist to PATH
for P in ~/usr ~; do
	if [ -d "${P}/bin" ]; then
		PATH="${P}/bin:${PATH}"
	fi
	if [ -d "${P}/man" ]; then
		MANPATH="${P}/man:${MANPATH}"
	fi
	if [ -d "${P}/share/man" ]; then
		MANPATH="${P}/share/man:${MANPATH}"
	fi
done

# Sun Java install for versions less than 6 on debian is a bit stupid
# Java 6 deb is non-stupid; maybe I can soon remove this block
if [ -d /usr/lib/j2sdk*/bin ] ; then
	for P in /usr/lib/j2sdk*/jre/bin /usr/lib/j2sdk*/bin; do
    	PATH="${PATH}:${P}"
	done
fi

# Who keeps creating these stupid empty directories? Nautilus, I think.
for d in ~/{Desktop,Documents,Music,Videos,Pictures,Public,Templates}; do
	[ -d "$d" ] && rmdir --ignore-fail-on-non-empty "$d"
done

# Manage ~/tmp. If this is the only login,
if [ "$(who | grep ^$USER | wc -l)" = "1" ]; then
	echo "Flushing ~/tmp"
	rm -rf "$HOME/.old-tmp"
	mv "$HOME/tmp" "$HOME/.old-tmp"
	mkdir "$HOME/tmp"
else
	echo "Already logged in; not flushing ~/tmp"
fi

if [ -d "$HOME/tmp" ]; then
	export TMPDIR=$HOME/tmp
	export TEMP=$HOME/tmp
fi

# I can't specify a nice switch in screen's configuration files, but it does
# interpret environment variables, so I can specify host-specific changes here.
# See etc/dotfiles/screenrc for details.
case "`hostname`" in
	io|kino|fiona)
		SCREEN_CK='` '
		SCREEN_CKR='bt'
		;;
	*)
		# Default screen behavior
		SCREEN_CK=`/bin/echo -e '\01a'`
		SCREEN_CKR='^A'
		;;
esac
case "`hostname`" in
	io)		SCREEN_CL='kg'; PS1_HOSTCOLOR='32';;
	kino)	SCREEN_CL='km'; PS1_HOSTCOLOR='35';;
	seiko)	SCREEN_CL='kr'; PS1_HOSTCOLOR='31';;
esac

# By default mail spool on ubuntu is nonexistent, if so start mutt looking
# somewhere else.
if [ ! -d "$MAIL" ]; then
	# XXX don't really know the best thing to do here
	MAIL=~/var/mail/inbox/
fi

if [ "$MANPATH" ]; then
	export MANPATH
fi
export SCREEN_CK
export SCREEN_CKR
export SCREEN_CL
export PS1_HOSTCOLOR
export GIT_PAGER=
export TEXINPUTS=$HOME/lib/latex2e/:
export PYTHONPATH=lib:$HOME/lib/python
export PYTHONSTARTUP=$HOME/.pythonrc.py
export PYTHONDOCS=/usr/share/doc/python-doc/html
export CLASSPATH=.:$HOME/lib/java
export EDITOR=vim
export PAGER=less
export LESS=-R
# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
#export HISTCONTROL=erasedups
export HISTCONTROL=ignoredups:ignorespace
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=1000
export HISTFILESIZE=2000
export TZ=America/New_York
# This is no good with new gnome's im-switch...
#export GTK_IM_MODULE="scim"
#export XMODIFIERS="@im=SCIM"

# Settings for virtualenvwrapper and pip
export WORKON_HOME="$HOME/var/virtualenvs"
export PIP_VIRTUALENV_BASE="$WORKON_HOME"
export PIP_RESPECT_VIRTUALENV=true

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Ensure virtualenvwrapper directory exists
if [ -x /usr/bin/virtualenv -a ! -d "$WORKON_HOME" ]; then
	mkdir "$WORKON_HOME"
fi

# if this is bash, include .bashrc if it exists.
if [ "$BASH_VERSION" -a -f ~/.bashrc ]; then
   . ~/.bashrc
fi

# vim: set ft=sh :
