#!/bin/sh
echo "Executing ~/.xsession" 2>&1

if [ "$WINDOW_MANAGER" ]; then
	echo Warning: ~/.xsession overriding previous WINDOW_MANAGER="$WINDOW_MANAGER"
else
	export WINDOW_MANAGER=xmonad
fi

gnome-settings-daemon &
xsetroot -cursor_name left_ptr
# Gnome 3 can't fucking do display settings anymore. Wat. Try to set them up in
# a sane way.
if 
	xrandr --query --current | grep -q "HDMI1 connected"
then
	xrandr \
		--output HDMI2 --off \
		--output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal \
		--output DP1 --off \
		--output eDP1 --mode 1360x768 --pos 1920x312 --rotate normal
else
	xrandr \
		--output HDMI2 --off \
		--output HDMI1 --off \
		--output DP1 --off \
		--output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal
fi

# gnome doesn't have its fucking shit together with multiple-resolution
# displays. This command must always come after the xrandr command.
gsettings set org.gnome.desktop.interface text-scaling-factor '1.0'
# gnome is recently fucking up my keyboard settings
setxkbmap -model pc104 -layout us -option ctrl:nocaps
# gnome is doing an awesome new thing where it hides my fucking cursor
dconf write /org/gnome/settings-daemon/plugins/cursor/active false


case "`hostname`" in
	# only bash sets $HOSTNAME
	kino)
		;;
	yuki)
		# I don't know why, but key repeat is disabled by default for some keys
		# on my Fujitsu u904 laptop.
		xset r 113 r on
		xset r 116 r on
		stalonetray &
		pasystray &
		nm-applet &
		google-chrome &
		(ssh-add && xchat) &
		;;
esac

# A notification daemon, at least until I find something better. Good to get
# this up after xchat to avoid the blast of notifications. Need a utility for
# viewing past notifications.
for f in notification-daemon notify-osd
do
	if [ -x /usr/lib/"$f"/"$f" ]; then
		/usr/lib/"$f"/"$f" &
		break
	fi
done

if which feh && [ -e $HOME/.wallpaper ]; then
	feh --bg-scale $HOME/.wallpaper &
fi

# (zenity --question --text "Tunnel to seiko?" && ssh -L9091:localhost:9091 -L6994:localhost:6994 -M seiko sleep 300) &
# (zenity --question --text "Tunnel to tilde.town?" && ssh -L9119:localhost:119 tilde.town sleep 300) &

if [ "$WINDOW_MANAGER" ]; then
	exec "$WINDOW_MANAGER"
else
	xmessage -timeout 5 "Window manager specified in .xsession not found." &
	exec xterm
fi
