# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/mike/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

# maybe these should be in a .profile.local?
export JELLYDOUGHNUT=~/mnt/jellydoughnut
export MED_EXEC_PATH=$JELLYDOUGHNUT/lib/med

source ~/.bash_aliases
